server:
  port: 8000
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info